; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	etlcpp/Embedded Template Library@^20.38.2
	thijse/ArduinoLog@^1.1.1
build_unflags =
	-std=gnu++11
build_flags =
 	-std=c++17
	-std=gnu++17
	-Wall
	-Wextra
	-O0
	-fdata-sections -ffunction-sections -Wl,--gc-sections
	--specs=nano.specs
debug_tool = esp-prog
build_type = debug
debug_init_break = tbreak setup
test_framework = googletest
